### PR TITLE
Automation for Mac

### PR DESCRIPTION
**Pull request by Emirhan-Atabay**
# Pull Request Checklist
Automates and simplifies the building process on Mac.

## Author

- [x] Built code and tested locally
- [x] Removed any TODOs, etc.
- [x] Metioned the issue this PR closes
- [x] Good description of what the PR does written

## Reviewer

- [ ] Built and tested code locally
- [ ] Fully understood the PR
- [ ] All open conversations resolved

### CODE REVIEW

**Comment by Emirhan-Atabay** [comment]
#53

**Comment by TuCl** [comment]
After clicking enter inside the Mac Terminal a new Window opens with this error: 

cd .; source ./settings.sh; sh ./hub_start.sh
source: no such file or directory: ./settings.sh
sh: ./hub_start.sh: No such file or directory

cd .; source ./settings.sh; sh ./enddevice_start.sh
source: no such file or directory: ./settings.sh
sh: ./enddevice_start.sh: No such file or directory

**Comment by Emirhan-Atabay** [comment]
Okay that should not actually be so. It does not recognize your settings.sh.
I am thinking of a solution for this problem.

"sh file should be started from terminal not by "click"" I think that's easier for the users. You can start it from the terminal too. The users should decided it for their own.

**Comment by Emirhan-Atabay** [comment]
Do you tried to double click on autostart.sh without trying to start it with the Terminal? It's possible that bash don't like this command: ```BASEDIR=$(dirname "$0")```. It's not working when you try to start it with the Terminal. 
Try this instead:
Go to the autostart.sh file and right click on it, select open with Terminal. I think I should change that anyway so that you can open it with the Terminal too.

**Comment by Emirhan-Atabay** [comment]
Okay, it should work now!

**Pull request merged**
